In [1]:
import numpy
import scipy
import scipy.ndimage
import matplotlib.pyplot as plt
import queue

In [58]:
def load():
    with open("../dat/day11.txt") as f:
        for ll in f:
            energy = [ int(xx.strip()) for xx in ll.strip() ]
            yield energy

energy = numpy.array(list(load()))

In [54]:
def adjacent(xx, yy, ww, hh):
    for ii in (-1, 0, 1):
        for jj in (-1, 0, 1):
            if ii == 0 and jj == 0:
                continue
            x = xx + ii
            y = yy + jj
            if x < 0 or y < 0:
                continue
            elif x >= ww or y >= hh:
                continue
            yield x, y

def step(energy):
    num_flashes = 0
    energy = energy + 1
    flashers = list( numpy.argwhere(energy > 9) )
    while len(flashers) > 0:
        num_flashes += 1
        yy, xx = flashers.pop(0)
        for y, x in adjacent(yy, xx, energy.shape[0], energy.shape[1]):
            if energy[y][x] < 9:
                energy[y][x] += 1
            elif energy[y][x] == 9:
                energy[y][x] = 10
                flashers.append((y, x))
    
    flashers = numpy.argwhere(energy > 9)
    for yy, xx in flashers:
        energy[yy][xx] = 0

    return energy, num_flashes

total_flashes = 0
for ii in range(100):
    energy, num_flashes = step(energy)
    total_flashes += num_flashes
print(energy)
print(total_flashes)

[[1 2 3 9 9 0 0 0 0 9]
 [2 4 0 0 0 0 7 6 9 6]
 [3 0 0 0 0 7 4 3 3 6]
 [9 0 0 0 0 6 3 3 3 7]
 [9 4 0 0 0 7 4 4 4 7]
 [5 6 7 8 0 0 5 4 2 6]
 [9 4 4 5 7 0 9 9 6 5]
 [8 5 5 4 5 8 6 6 9 4]
 [9 0 8 6 9 6 5 5 7 4]
 [0 0 0 0 7 5 5 5 6 9]]
1673


In [59]:
total_flashes = 0
steps = 0
while True:
    steps += 1
    energy, num_flashes = step(energy)
    total_flashes += num_flashes
    if numpy.count_nonzero(energy) == 0:
        break
print(energy)
print(total_flashes)
print(steps)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
8282
505
